"""add meeting_date and action_deadline to cases

Revision ID: e2f058979d65
Revises: 
Create Date: 2026-06-01 22:02:11.940799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f058979d65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('meeting_date', sa.Date(), nullable=True))
    op.add_column('cases', sa.Column('action_deadline', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'action_deadline')
    op.drop_column('cases', 'meeting_date')
    # ### end Alembic commands ###
